# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f19a1853139599cd56fc7e2a74757a253b81ae33a57f2d69fd52e2ddcf3f4f9c070ed3742637f1f74f5137eb6170f52ec15ea6a3294aecb09066811e5be827d0

test:
  secret_key_base: 6398b9ce7e813abbae2c662e150b5f89547b1d84b06634165d0b7675b3e8f10090653ffcb3868eab5da039359340cf9034bad7751e792a3cddf52d2c2801f6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
